### ISSUE TITLE
How do you configure the personal access token?

### ISSUE THREAD

**Issue by atrauzzi** [jonabc/sync-task-issues#24]
It's mentioned in the docs, but not detailed in any way?

**Comment by jonabc** [comment]
:wave: hi @atrauzzi I'm not entirely certain what you mean, but looking at the README the only thing that seems to be missing is the name of the input to use with the token.  If that's the problem, you can set it using the [github_token](https://github.com/jonabc/sync-task-issues/blob/28416dca4c0eeca5b6c1a2a0957f86a6f76d8730/action.yml#L4) input, and I can update the README to include that in the example.

If that's not what the problem is, could you clarify your question at all?

**Comment by atrauzzi** [comment]
That's exactly it! :smile:
